# welcome 

In [1]:
import numpy as np

In [2]:
print("Hello World")

Hello World


In [3]:
myarr = np.array([[3,4,9,8,7,6,5,4,4,]])

In [4]:
myarr

array([[3, 4, 9, 8, 7, 6, 5, 4, 4]])

In [5]:
myarr[0]

array([3, 4, 9, 8, 7, 6, 5, 4, 4])

In [6]:
myarr[0,4]

7

In [7]:
myarr.shape

(1, 9)

In [8]:
myarr.dtype

dtype('int32')

 # array creation : conversion from other datastructures
 

# hello 

In [9]:
listarray = np.array([[1,2,3],[4,4,5],[7,8,9]])

In [10]:
listarray

array([[1, 2, 3],
       [4, 4, 5],
       [7, 8, 9]])

In [11]:
listarray.dtype

dtype('int32')

In [12]:
listarray.shape

(3, 3)

In [13]:
listarray.shape

(3, 3)

In [14]:
listarray.size

9

In [15]:
zeroes = np.zeros((2,4))

In [16]:
zeroes

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
range_function = np.arange(10)

In [18]:
range_function

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
linspace = np.linspace(1,2,5)

In [20]:
linspace

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [21]:
empty = np.empty((4,5))

In [22]:
empty

array([[8.48798316e-314, 1.14223857e-311, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [1.14223857e-311, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 3.94004319e+180],
       [1.65081059e-086, 1.62672658e-086, 1.62672658e-086,
        3.00947434e-067, 5.60235584e-067],
       [5.98131470e-154, 6.52016598e+252, 4.83781471e+276,
        1.62672658e-086, 1.62672658e-086]])

In [23]:
empty_like = np.empty_like(linspace)

In [24]:
empty_like 

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [25]:
ide = np.identity(45)

In [26]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [27]:
ide.shape

(45, 45)

In [28]:
arr = np.arange(99)

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [30]:
arr = arr.reshape(3,33)

In [31]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [32]:
arr = arr.ravel()

In [33]:
arr.shape

(99,)

In [34]:
x = [[1,2,3,3],[3,4,5,6,],[5,6,7,7]]

In [35]:
ar = np.array(x)

In [36]:
ar

array([[1, 2, 3, 3],
       [3, 4, 5, 6],
       [5, 6, 7, 7]])

In [37]:
ar.sum(axis=0)

array([ 9, 12, 15, 16])

In [38]:
ar.sum(axis=1)

array([ 9, 18, 25])

In [39]:
ar=ar.T

In [40]:
ar

array([[1, 3, 5],
       [2, 4, 6],
       [3, 5, 7],
       [3, 6, 7]])

In [41]:
ar.flat

In [42]:
for item in ar.flat:
    print(item)

1
3
5
2
4
6
3
5
7
3
6
7


In [43]:
ar.ndim

2

In [44]:
ar.size

12

In [45]:
ar.nbytes

48

In [46]:
one = np.array([1,4,5,6677,8,999999,0])

In [47]:
one.argmax()

5

In [48]:
one.argmin()

6

In [49]:
one.argsort()

array([6, 0, 1, 2, 4, 3, 5], dtype=int64)

In [50]:
ar.argmin()

0

In [51]:
ar

array([[1, 3, 5],
       [2, 4, 6],
       [3, 5, 7],
       [3, 6, 7]])

In [52]:
ar.argmin()

0

In [53]:
ar.argmax()

8

In [54]:
ar.argmax(axis=0)

array([2, 3, 2], dtype=int64)

In [55]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [56]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [57]:
ar.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]], dtype=int64)

In [58]:
ar2 = np.array([[1,3,4],[2,3,4],[1,2,34],[2,3,4]])

In [59]:
ar*ar2

array([[  1,   9,  20],
       [  4,  12,  24],
       [  3,  10, 238],
       [  6,  18,  28]])

In [60]:
np.sqrt(ar)

array([[1.        , 1.73205081, 2.23606798],
       [1.41421356, 2.        , 2.44948974],
       [1.73205081, 2.23606798, 2.64575131],
       [1.73205081, 2.44948974, 2.64575131]])

In [61]:
ar.sum()

52

In [62]:
ar.max()

7

In [63]:
np.where(ar>5)

(array([1, 2, 3, 3], dtype=int64), array([2, 2, 1, 2], dtype=int64))

In [64]:
np.count_nonzero(ar)

12

In [65]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [66]:
ar[1,2] = 0

In [67]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2, 2, 3, 3, 3], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1, 2, 0, 1, 2], dtype=int64))

In [68]:
import sys

In [71]:
py_ar =[0,4,6,5]

In [72]:
np_ar = np.array(py_ar)

In [74]:
sys.getsizeof(1)*len(py_ar)

112